D22 Hoàng Trung Hiếu
bdt-proptit/seabattle pull request #22
Opened 2023-11-27 11:06 UTC by jinjja9

2023-11-27 16:25 UTC, quochung-cyou requested changes

2023-11-27 16:25 UTC, quochung-cyou commented on Hoàng Trung Hiếu/UML/Class Diagram.jpg
- trong manager anh thấy player1 là Player thì class Player ở đâu em
- row, column ở trong manager để làm gì nhỉ
- trong map row và column để làm gì nhỉ 
- type của ship thì nên là string sẽ ổn hơn, hoặc tốt hơn nữa thì em xem enum
- row, column của ship thì em định lưu là điểm đầu hay điểm cuối của 1 con tàu.

2023-11-27 16:25 UTC, quochung-cyou commented on Hoàng Trung Hiếu/UML/Class Diagram.jpg
em sửa lại sau resolve comment nhé

2023-11-27 16:25 UTC, quochung-cyou commented on Hoàng Trung Hiếu/UML/Activity Diagram.jpg
cái này người chơi 1 chọn toạ độ sau đó mới đến ng chơi 2 chọn toạ độ, tại mình vẫn đang chạy tuần tự (tương tự check tàu chìm và check bắn full map)

2023-11-29 17:55 UTC, jinjja9 commented on Hoàng Trung Hiếu/UML/Class Diagram.jpg
em đã sửa ạ

2023-11-29 18:00 UTC, quochung-cyou requested changes

2023-11-29 18:00 UTC, quochung-cyou commented on Hoàng Trung Hiếu/UML/Class Diagram.jpg
- sao player1, player 2 lại type là ship, name1 name 2 để làm gì nhỉ
- thực tế thì e k canà lưu shooting point và damagepoint, có thể tập trung nó về 1 bảng để lưu trạng thái hiện tại từng ô. ví dụ lưu nnay thì giờ cho 1 toạ độ 5,10, cần check nó bị băns hay bị damage gì đấy lại phải for 1 lượt qua array xem có trùng cái nào đã bắn rồi không ?
-

2023-11-29 18:01 UTC, quochung-cyou requested changes

2023-11-29 18:01 UTC, quochung-cyou commented on Hoàng Trung Hiếu/UML/Activity Diagram.jpg
cái này chưa được sửa nhưng đã đánh resolve

2023-12-06 03:04 UTC, merged