D22 Bùi Quang Đạt
bdt-proptit/seabattle pull request #24
Opened 2023-11-27 11:28 UTC by buiquangdat1710

2023-11-27 16:18 UTC, quochung-cyou requested changes

2023-11-27 16:18 UTC, quochung-cyou commented on Bùi Quang Đạt/SeaBattleUML.mdj
em render thành ảnh hay pdf gì đó nhé

2023-11-27 16:18 UTC, quochung-cyou commented on Bùi Quang Đạt/SeaBattleUML.mdj
@buiquangdat1710

2023-11-27 16:52 UTC, buiquangdat1710 commented on Bùi Quang Đạt/SeaBattleUML.mdj
Dạ vâng ạ

2023-11-29 16:53 UTC, quochung-cyou approved these changes
LGTM

2023-11-29 16:53 UTC, merged