D22 Trần Đức Chính
bdt-proptit/seabattle pull request #26
Opened 2023-11-27 11:46 UTC by TrDucChinh

2023-11-27 16:18 UTC, quochung-cyou requested changes

2023-11-27 16:18 UTC, quochung-cyou commented on Trần Đức  Chính/UML/UML_ClassDiagram.jpg
- em sửa lại 1 số chính tả (Gird -> grid)
- cái này thì biến nào sẽ đánh dấu được lượt hiện tại của người chơi nào
- cái này thì làm sao để biết thuyền nào là thuyền nào, chắc anh đoán cái placeShip của em là đặt thuyền thì các thuyền đều là như nhau, chỉ là chuyển string ở toạ độ nào đó thành gì đó. cái này cx ok nhma sau vd vẫn với logic này hiển thị lên chỗ khác mà hình thuyền khác nhau thì k  xử lí đc
- nếu k phải ý bên trên, mà em định dùng string để đánh dấu 1 ô là thuyền gì, bị phá chưa, .... thì em tham khảo thêm enum

2023-11-27 16:18 UTC, quochung-cyou commented on Trần Đức  Chính/UML/ActivityDiagram.jpg
ok

2023-11-27 16:18 UTC, quochung-cyou commented on Trần Đức  Chính/UML/UML_ClassDiagram.jpg
em sửa sau đó resolve cmt này

2023-11-28 04:25 UTC, TrDucChinh commented on Trần Đức  Chính/UML/UML_ClassDiagram.jpg
-em sẽ cho đặt lần lượt từ thuyền 1x5 đến thuyền 1x2 ạ vì đây là MVP nên mọi điều kiện nhập là lý tưởng ạ. Còn trong trường hợp không lý tưởng em có thêm hàm checkCoordinate để tránh nhập tọa độ ngoài bảng ạ. Và trong placeShip em có kiểm tra tọa độ có bị chéo không nếu chéo thì yêu cầu nhập lại ạ
![ClassDiagram](https://github.com/bdt-proptit/seabattle/assets/140167017/ee9a9b51-1554-4ca2-9735-c2d0ca2b5c31)

2023-11-28 11:13 UTC, quochung-cyou commented on Trần Đức  Chính/UML/UML_ClassDiagram.jpg
tức là placeShip của em sẽ truyền 4 toạ độ (x1,y1) (x2,y2) à

2023-11-30 07:34 UTC, quochung-cyou approved these changes

2023-11-30 07:34 UTC, merged