first commit
bdt-proptit/seabattle pull request #8
Opened 2023-11-26 19:14 UTC by TanaKeKe

2023-11-28 09:49 UTC, quochung-cyou requested changes

2023-11-28 09:49 UTC, quochung-cyou commented on Phan Thanh Tân/UML/image.png
- như này thì trong board không có biến nào lưu dữ liệu ô đó bị bắn trúng, ô đó là thuyền, ...
- code chứa thông tin ví dụ khi đặt thuyền thì độ dài, toạ độ các thứ ở đâu nhỉ, gần như k có biến nào lưu thông tin mấy cái đấy

2023-11-28 13:20 UTC, TanaKeKe commented on Phan Thanh Tân/UML/image.png
- Em định cho ô bị bắn trúng hiển thị lên luôn màn hình + so sánh với bảng ẩn của bảng hiện tại ạ.
- code chứa thông tin ví dụ khi đặt thuyền độ dài, tọa độ thì em sẽ để phần player làm việc trên Board lúc đầu vào khi mà gọi player trong phương thức play() của lớp Process luôn ạ.

2023-11-28 15:32 UTC, quochung-cyou commented on Phan Thanh Tân/UML/image.png
theo class diagram thì với đúng cái ảnh kia, chỉ với số biến và phương thức như kia thì em có code ra được không

2023-11-28 18:01 UTC, TanaKeKe commented on Phan Thanh Tân/UML/image.png
Vâng ạ, em cảm ơn, em sẽ rút kinh nghiệm sắp tới ạ.

2023-11-29 02:53 UTC, quochung-cyou commented on Phan Thanh Tân/UML/image.png
rút kinh nghiệm là làm lại cái uml đi nhé, em cứ đẩy commit mới lên thì nó vẫn tự động vào pull request này

2023-12-05 09:50 UTC, merged