D22 le dinh hiep
bdt-proptit/seabattle pull request #9
Opened 2023-11-27 00:28 UTC by MemoGlow

2023-11-28 10:30 UTC, quochung-cyou requested changes

2023-11-28 10:30 UTC, quochung-cyou commented on Lê Đình Hiệp/UML/class.png
- em lưu 2 player thì tổng lại có 4 bảng, em xem liệu có làm 2 bảng thôi đc không, tứclà myBoard và mình handle độc lập
- - direction ở ship em tham khảo dùng enum
- board lưu dạng int thì r thì làm sao để định được cái ô nào là thuyền, ô nào trống, ô nào ... ok thì em có thể tự định nghĩa là "1" là thuyền patrol đi, "2" là thuyền gì đó, "3 là nổ, nhma thế thì tại nhiều file code em phải if else với đống char này nó bị rời rạc (ví dụ sửa hiển thị nổ thành "5", thì chỗ khác cũng phải sửa int như thế), em có thể tham khảo dùng enum thay vì char

2023-11-30 00:44 UTC, MemoGlow commented on Lê Đình Hiệp/UML/class.png
dạ vâng ạ

2023-11-30 07:35 UTC, quochung-cyou approved these changes

2023-11-30 07:35 UTC, merged